name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install build tools
      run: pip install setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Setup SSH for gcloud
      env:
        GCP_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GCP_IP_EXTERNAL: ${{ secrets.GCP_IP_EXTERNAL }}
      run: |
        mkdir -p ~/.ssh
        echo "$GCP_SSH_PRIVATE_KEY" > ~/.ssh/google_compute_engine
        chmod 600 ~/.ssh/google_compute_engine
        ssh-keyscan -t rsa [GCP_IP_EXTERNAL] >> ~/.ssh/known_hosts
    - name: Authenticate with GCP
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" | base64 --decode > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project memoflash

    - name: Copy files to GCP
      run: gcloud compute scp ./ ${{ secrets.GCP_VM_NAME }}:~/app/ --recurse --zone ${{ secrets.GCP_ZONE }}

    - name: SSH and Restart server
      run: |
        gcloud compute ssh ${{ secrets.GCP_VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "sudo supervisorctl restart all"

