name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: memoflash

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install build tools
        run: pip install setuptools wheel

      - name: Setup SSH for gcloud
        env:
          GCP_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GCP_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$GCP_SSH_PRIVATE_KEY" > ~/.ssh/google_compute_engine
          echo "$GCP_SSH_PUBLIC_KEY" > ~/.ssh/google_compute_engine.pub
          chmod 600 ~/.ssh/google_compute_engine
          chmod 644 ~/.ssh/google_compute_engine.pub
          ssh-keyscan -t rsa 34.171.3.249 >> ~/.ssh/known_hosts

      - name: Authenticate with GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project memoflash

      - name: Copy files to GCP
        env:
          GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_MAIN_DIR: ${{ secrets.GCP_MAIN_DIR }}
          GCP_USR: ${{ secrets.GCP_USR }}
        run: gcloud compute scp /home/runner/work/memoflash_back/memoflash_back $GCP_USR@$GCP_VM_NAME:$GCP_MAIN_DIR --recurse --zone $GCP_ZONE

      - name: Change ownership
        env:
          GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_MAIN_DIR: ${{ secrets.GCP_MAIN_DIR }}
          GCP_USR: ${{ secrets.GCP_USR }}
        run: |
          gcloud compute ssh $GCP_USR@$GCP_VM_NAME --zone $GCP_ZONE --command "sudo chown -R $GCP_USR:$GCP_USR $GCP_MAIN_DIR/memoflash_back"

      - name: Set execute permission for start.sh
        env:
          GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_MAIN_DIR: ${{ secrets.GCP_MAIN_DIR }}
          GCP_USR: ${{ secrets.GCP_USR }}
        run: |
          gcloud compute ssh $GCP_USR@$GCP_VM_NAME --zone $GCP_ZONE --command "sudo chmod +x $GCP_MAIN_DIR/memoflash_back/start.sh"

      - name: SSH and Restart server
        env:
          GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_MAIN_DIR: ${{ secrets.GCP_MAIN_DIR }}
          GCP_USR: ${{ secrets.GCP_USR }}
        run: |
          gcloud compute ssh $GCP_USR@$GCP_VM_NAME --zone $GCP_ZONE --command "$GCP_MAIN_DIR/memoflash_back/start.sh $GCP_MAIN_DIR/memoflash_back/.env"
