name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install build tools
      run: pip install setuptools wheel
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Copy files to GCP
      run: gcloud compute scp ./ ${{ secrets.GCP_VM_NAME }}:~/app/ --recurse --zone ${{ secrets.GCP_ZONE }}
    - name: SSH and Restart server
      run: |
        gcloud compute ssh ${{ secrets.GCP_VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "sudo supervisorctl restart all"
